apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-image
        volumeMounts:
          - name: storage
            mountPath: /mnt/disk1
        image: nginx
        ports:
        - containerPort: 80
      volumes:
          - name: storage
            azureDisk:
              kind: Managed
              diskName: clusterdisk
              diskURI: /subscriptions/20c6eec9-2d80-4700-b0f6-4fde579a8783/resourceGroups/MC_test-grp_democluster_northeurope/providers/Microsoft.Compute/disks/clusterdisk
